CREATE TABLE `automation_video_assets` (
	`id` text PRIMARY KEY NOT NULL,
	`workspace_id` text NOT NULL,
	`uploaded_by` text NOT NULL,
	`name` text NOT NULL,
	`file_url` text NOT NULL,
	`file_type` text NOT NULL,
	`mime_type` text NOT NULL,
	`size` integer NOT NULL,
	`status` text DEFAULT 'available' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `automation_video_tasks` (
	`id` text PRIMARY KEY NOT NULL,
	`workspace_id` text NOT NULL,
	`created_by` text NOT NULL,
	`title` text NOT NULL,
	`prompt` text NOT NULL,
	`script_language` text NOT NULL,
	`keywords` text NOT NULL,
	`script_text` text,
	`material_source` text NOT NULL,
	`material_asset_ids` text NOT NULL,
	`stitch_mode` text NOT NULL,
	`transition_mode` text NOT NULL,
	`video_ratio` text NOT NULL,
	`clip_duration` text NOT NULL,
	`match_by_script` integer DEFAULT true NOT NULL,
	`voice_mode` text NOT NULL,
	`voice_service` text NOT NULL,
	`voice_name` text NOT NULL,
	`voice_volume` text NOT NULL,
	`voice_speed` text NOT NULL,
	`music_source` text NOT NULL,
	`music_volume` integer NOT NULL,
	`subtitle_enabled` integer DEFAULT true NOT NULL,
	`subtitle_font` text NOT NULL,
	`subtitle_position` text NOT NULL,
	`subtitle_style` text NOT NULL,
	`subtitle_size` text NOT NULL,
	`subtitle_color` text NOT NULL,
	`subtitle_background` integer DEFAULT true NOT NULL,
	`packaging_options` text NOT NULL,
	`status` text DEFAULT 'pending_review' NOT NULL,
	`result_summary` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
